### PR TITLE
enable cryptsetup usage for luks

### PR DESCRIPTION
**Pull request by d4v3y0rk**
This simple change enables the usage of cryptsetup to open encrypted files that are luks encrypted.

### CODE REVIEW

**Comment by WSLUser** [comment]
This is included as part of #115.

**Comment by d4v3y0rk** [comment]
@WSLUser will this PR be merged or just the change? I was hoping to be a contributor to the project officially...

**Comment by WSLUser** [comment]
I was just mentioning. Since mine is larger scope, yours is more likely to get merged first.

**Comment by eggbean** [comment]
I have been looking into this, and I think this line also needs to be set so that hardware acceleration is used for disk file transfer:

https://github.com/microsoft/WSL2-Linux-Kernel/blob/db998769a92eb01159c74b1f461b502a49cc3aa2/Microsoft/config-wsl#L2603

`CONFIG_CRYPTO_AES_NI_INTEL=y`

I think disk speeds will be slower without this. I'm not sure if AMD CPUs use the same setting.

**Comment by WSLUser** [comment]
Please test first. It's possible hardware acceleration isn't possible yet. I would suggest using my config, which already boosts perf but doesn't have this config option enabled. Compile it and then compile another with this config option being the only change and do a check with Process Explorer. I have an updated PR though: https://github.com/microsoft/WSL2-Linux-Kernel/pull/176

**Comment by jdoe1024** [comment]
eaa73a2d52ff620a8c71ba23d57a73a0e33eae03 set `CONFIG_DM_CRYPT` in WSL2 kernel configuration so it should be available since 5.4.91 (and the 5.10 branch). My WSL2 kernel install is still using 5.4.72 though, so I guess it is only distributed to insiders yet.

This PR can probably be closed then... even if the owners of this repository do not seem to care about the PRs anyway.

**Pull request closed without merging**
