### PR TITLE
Upstream Kernel to 5.4.70

### PR DESCRIPTION
**Pull request by johnmart19**
Upstream Kernel to 5.4.70

### CODE REVIEW

**Comment by WSLUser** [comment]
Does this retain the custom patches such as Free Page Reporting?

**Comment by johnmart19** [comment]
This is just standard kernel upstream, all custom Microsoft staff is
untouched and working stable as usual without additional problems.

пт, 9 окт. 2020 г., 18:25 WSLUser <notifications@github.com>:

**Comment by WSLUser** [comment]
yes I looked at your fork and see it's still there. Not sure if there were any patches to those specific files in hv that would conflict with upstream. If you found nothing then awesome work bumping this up. I would expected it to less than trivial.

**Comment by WSLUser** [comment]
Also keep in mind, they may have already bumped it internally and not released it into the github yet. It's not as maintained as it should.

**Comment by justinkb** [comment]
commit 71d65a3fc62888505bcaff5eaabf8ffc6b6d7be2 from 5.4.53 is missing from this

**Comment by Biswa96** [comment]
There is already a WSl Linux kernel 5.4.51 in the release. This _I-don't-know-what-I-am-doing_ PR can be closed.

**Comment by Biswa96** [comment]
There is already a WSL Linux kernel 5.4.51 in the release page. This _I-don't-know-what-I-am-doing_ PR can be closed.

**Comment by justinkb** [comment]
> There is already a WSL Linux kernel 5.4.51 in the release page. This _I-don't-know-what-I-am-doing_ PR can be closed.

I hope you realize the number 70 is greater than the number 51

**Comment by WSLUser** [comment]
This PR can be closed. The latest release shows 5.4..83 which is newer than this PR.

**Pull request closed without merging**
