### PR TITLE
Fix package installation instruction, add apt update command

### LINKED ISSUE #3: mistype in README-Microsoft.WSL2
step 2 should be (missing command among stars):
$ sudo *apt* install build-essential flex ...

### PR DESCRIPTION
**Pull request by timvisee**
Fixes #3

### CODE REVIEW

**Comment by timvisee** [comment]
Bump. Approved but still not merged.

**Comment by sethbergman** [comment]
Why hasn't this been merged? It's a simple change but very important for user documentation. Bumping this

**Comment by mausch** [comment]
Dear Microsoft, there's loads of PRs about this, please merge any of them?

https://github.com/microsoft/WSL2-Linux-Kernel/pull/32
https://github.com/microsoft/WSL2-Linux-Kernel/pull/36
https://github.com/microsoft/WSL2-Linux-Kernel/pull/54
https://github.com/microsoft/WSL2-Linux-Kernel/pull/200

**Comment by jiayali-ms** [comment]
Thank you for your contribution. The WSL team has discussed and decided that the WSL 2 Linux kernel GitHub repo is not taking pull requests. The WSL 2 Linux kernel repo was always intended to provide the additional infrastructure necessary to build and release the kernel component of WSL 2. It was never designed to replace the current existing community and feedback channels for WSL, especially through https://github.com/microsoft/WSL. This is why we are not accepting issues or pull requests through this repository.
 
We understand that this should have been better communicated and implemented from the beginning. While we understand that it is frustrating to have a PR closed, it is never our intention to ignore feedback or stifle community discussions. We are taking this opportunity to increase transparency on how we work with the WSL community and ensure all members are routed to the appropriate resources. 
 
If you would like contribute to, discuss, or report an issue relating to WSL, or the WSL 2 Linux kernel configuration, please do so at the WSL GitHub. The team is actively monitoring and responding to user feedback there: https://github.com/microsoft/WSL.
 
The WSL 2 Linux kernel is based on the Linux version from https://www.kernel.org/. If you would like to contribute to or report an issue on the Linux kernel in general, please do so on the upstream Linux GitHub: https://www.kernel.org/doc/html/latest/process/submitting-patches.html.

**Pull request closed without merging**
