### PR TITLE
Add scripts for building in a container

### PR DESCRIPTION
**Pull request by simonferquel**
This adds 2 scripts to the repo:
- build-ms-kernel.sh runs make with `-j <number of available procs>` to parallelize the build
- build-in-container.sh runs the build in a docker container (requires docker).

### CODE REVIEW

**Comment by Biswa96** [comment]
I am not sure if this is important or not. The `docker run` command contains your specific image `simonferquel/kernel-builder:ubuntu-18.04`. Shouldn't that be just the base image `ubuntu:18.04`.

**Comment by Biswa96** [comment]
I am not sure if this is important or not. The `docker run` command contains your specific image `simonferquel/kernel-builder:ubuntu-18.04`. Shouldn't that be just the base image `ubuntu:18.04`?

**Comment by simonferquel** [comment]
This is an Ubuntu base image + necessary packages to build the kernel

**Comment by jiayali-ms** [comment]
Thank you for your contribution. The WSL team has discussed and decided that the WSL 2 Linux kernel GitHub repo is not taking pull requests. The WSL 2 Linux kernel repo was always intended to provide the additional infrastructure necessary to build and release the kernel component of WSL 2. It was never designed to replace the current existing community and feedback channels for WSL, especially through https://github.com/microsoft/WSL. This is why we are not accepting issues or pull requests through this repository.
 
We understand that this should have been better communicated and implemented from the beginning. While we understand that it is frustrating to have a PR closed, it is never our intention to ignore feedback or stifle community discussions. We are taking this opportunity to increase transparency on how we work with the WSL community and ensure all members are routed to the appropriate resources. 
 
If you would like contribute to, discuss, or report an issue relating to WSL, or the WSL 2 Linux kernel configuration, please do so at the WSL GitHub. The team is actively monitoring and responding to user feedback there: https://github.com/microsoft/WSL.
 
The WSL 2 Linux kernel is based on the Linux version from https://www.kernel.org/. If you would like to contribute to or report an issue on the Linux kernel in general, please do so on the upstream Linux GitHub: https://www.kernel.org/doc/html/latest/process/submitting-patches.html.

**Pull request closed without merging**
