### PR TITLE
enable CONFIG_SECURITY_YAMA=y

### PR DESCRIPTION
**Pull request by therealkenc**
Ref [WSL#4286](https://github.com/microsoft/WSL/issues/4286). Aligns with stock Ubuntu kconfig. Brings back `/proc/sys/kernel/yama/ptrace_scope` which oddly enough is a WSL1 feature (ref [microsoft/WSL#121](https://github.com/microsoft/WSL/issues/121)).

### CODE REVIEW

**Comment by Biswa96** [comment]
It looks like some of your changes are added.

**Comment by WSLUser** [comment]
This is included as part of #115.

**Comment by therealkenc** [comment]
> This is included as part of #115.

image

Seriously. I'll take my (demonstrably low) chances here thanks.

**Comment by acepaceNS** [comment]
Available outside insider preview when?

**Pull request closed without merging**
